# @package _global_
defaults:
  - dataset: huggingface_upstagedialogues_dataset
  - architecture: huggingface_architecture
  - tuner: huggingface_tuner
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

package_name: upstage-nlp-baseline
project_dir: /data/ephemeral/${package_name}
connected_dir: /data/ephemeral/${package_name}

seed: 2024

split:
  train: train
  val: val
  test: test
  predict: predict

batch_size: 8

split_ratio: 0.1
target_column_name: summary
upload_user: EbanLee
model_type: kobart-summary-v3
pretrained_model_name: ${upload_user}/${model_type}
text_max_length: 1024

lr: 0.00002
t_max: 50
eta_min: 0.0000025
options:
  max_length: 512

monitor: val_loss
tracking_direction: min
patience: 3
min_delta: 0

devices: 1
accelerator: gpu
strategy: auto
log_every_n_steps: 10
precision: 16
accumulate_grad_batches: 1
epoch: 1024

model_name: HuggingFace
dataset_name: UpStageDialogues
mode: train

is_tuned: tuned
num_trials: 3
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}-${mode}
total_batch_size: bs${batch_size}x${devices}x${accumulate_grad_batches}
save_detail: ${upload_user}_${model_type}-text_max_length${text_max_length}-precision${precision}-${total_batch_size}
resumed_step: 0
ckpt_path: ${callbacks.model_checkpoint.dirpath}/epoch${epoch}.ckpt

submission_file_name: test
logit_name: ${save_detail}-epoch${epoch}-generation_max_length${options.max_length}
submission_name: ${save_detail}-epoch${epoch}-generation_max_length${options.max_length}

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}